'use strict';
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
const {chromium}=require('C:/Users/arthu/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
process.env.BRAVOPAY_API_KEY='QA_NOT_REAL';process.env.ORDER_SIGNING_SECRET='QA_ORDER_SECRET_NOT_REAL_12345678901234567890';process.env.GATE_PASSWORD='QA_GATE_NOT_REAL_123456';process.env.UPSTASH_REDIS_REST_URL='https://qa-redis.invalid';process.env.UPSTASH_REDIS_REST_TOKEN='QA_NOT_REAL';process.env.TICKET_VALID_UNTIL=new Date(Date.now()+90*86400000).toISOString();
const {sign,amount}=require('../lib/payment-shared');
const order={v:1,id:'tx_qa_demo',ref:'hp10_jovem_'+'c'.repeat(32),name:'Comprador de teste',ticket:'jovem',quantity:2,amount:amount('jovem',2),expires:Date.now()+86400000};
const data=new Map();
global.fetch=async(url,opts)=>{
 if(String(url).endsWith('/pipeline')){const [[op,...a]]=JSON.parse(opts.body);let result;if(op==='PING')result='PONG';else if(op==='GET')result=data.get(a[0])||null;else if(op==='SET'){if(a.includes('NX')&&data.has(a[0]))result=null;else{data.set(a[0],a[1]);result='OK';}}else if(op==='INCR'){result=Number(data.get(a[0])||0)+1;data.set(a[0],result);}else if(op==='EXPIRE')result=1;else if(op==='DEL')result=Number(data.delete(a[0]));else if(op==='EVAL'){const [,,ticket,used,blocked,now,checkin]=a;const rec=JSON.parse(data.get(ticket)||'null');if(!rec)result=['missing'];else if(rec.expires<=now)result=['expired'];else if(data.has(blocked))result=['revoked'];else if(data.has(used))result=['used',data.get(used)];else{data.set(used,checkin);result=['admitted',checkin];}}else throw Error(op);return {ok:true,json:async()=>[{result}]};}
 return {ok:true,json:async()=>({data:[{id:order.id,external_reference:order.ref,amount_cents:order.amount,method:'PIX',currency:'BRL',metadata:{ticket:order.ticket,quantity:2},status:'PAID'}]})};
};
const handlers={'/api/pix-status':require('../api/pix-status'),'/api/tickets':require('../api/tickets'),'/api/gate-session':require('../api/gate-session'),'/api/gate-check':require('../api/gate-check')};
const root=path.resolve(__dirname,'..');
const server=http.createServer(async(req,res)=>{try{let body='';for await(const part of req)body+=part;req.body=body?JSON.parse(body):{};res.status=c=>{res.statusCode=c;return res;};res.json=value=>{res.setHeader('Content-Type','application/json');res.end(JSON.stringify(value));return res;};const url=new URL(req.url,'http://localhost');if(handlers[url.pathname])return await handlers[url.pathname](req,res);const file=path.resolve(root,'.'+(url.pathname==='/'?'/index.html':url.pathname));if(!file.startsWith(root+path.sep)){res.statusCode=403;return res.end();}const mime={'.html':'text/html','.js':'text/javascript','.css':'text/css','.webp':'image/webp','.png':'image/png','.svg':'image/svg+xml'};res.setHeader('Content-Type',mime[path.extname(file)]||'text/plain');res.end(fs.readFileSync(file));}catch(e){res.statusCode=500;res.end('Local QA error');console.error(e.message);}});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://localhost:'+server.address().port;let browser;try{
 browser=await chromium.launch({channel:'msedge',headless:true,args:['--use-fake-device-for-media-stream','--use-fake-ui-for-media-stream']});const page=await browser.newPage({viewport:{width:390,height:844}});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.addInitScript(token=>sessionStorage.setItem('hp10_order_token',token),sign(order));
 await page.goto(base+'/obrigado.html');await page.locator('.entry-ticket').first().waitFor();assert.equal(await page.locator('.entry-ticket').count(),2);const downloadEvent=page.waitForEvent('download');await page.locator('.entry-ticket button').first().click();const download=await downloadEvent;await download.saveAs(path.join(root,'qa','ticket-demo.png'));await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:'qa/tickets-mobile.png',fullPage:true});
 await page.goto(base+'/portaria.html');await page.locator('#station').fill('Portaria QA');await page.locator('#password').fill(process.env.GATE_PASSWORD);await page.locator('#loginButton').click();await page.locator('#scannerPanel').waitFor({state:'visible'});
 await page.locator('#startCamera').click();await page.locator('#video').waitFor({state:'visible'});await page.locator('#stopCamera').click();assert.equal(await page.locator('#video').isHidden(),true);
 await page.locator('#qrFile').setInputFiles(path.join(root,'qa','ticket-demo.png'));await page.locator('#resultTitle').filter({hasText:'Ingresso válido'}).waitFor();await page.screenshot({path:'qa/portaria-valid-mobile.png',fullPage:true});await page.locator('#admitButton').click();await page.locator('#resultTitle').filter({hasText:'Entrada confirmada'}).waitFor();await page.screenshot({path:'qa/portaria-admitted-mobile.png',fullPage:true});
 await page.locator('#nextButton').click();await page.locator('#qrFile').setInputFiles(path.join(root,'qa','ticket-demo.png'));await page.locator('#resultTitle').filter({hasText:'Ingresso já utilizado'}).waitFor();assert.equal(await page.locator('#admitButton').isHidden(),true);await page.screenshot({path:'qa/portaria-used-mobile.png',fullPage:true});
 for(const width of [320,390,1440]){await page.setViewportSize({width,height:900});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);}
 await page.locator('#logout').click();await page.locator('#loginPanel').waitFor({state:'visible'});assert.deepEqual(errors,[]);console.log('PASS: dois ingressos, download PNG, QR lido da imagem, câmera simulada, consulta, entrada única, duplicado bloqueado, logout, responsivo 320/390/1440.');
 }finally{if(browser)await browser.close();server.close();}})().catch(e=>{console.error(e);process.exitCode=1;server.close();});
